name: Validate

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
  workflow_dispatch: {}

jobs:
  validate-python:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv (with cache)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}

      - name: Create venv
        run: uv venv --python ${{ matrix.python-version }}

      - name: Sync project (install deps)
        run: uv sync --locked --all-extras --dev

      - name: Lint
        run: uv run ruff check .

      - name: Check formatting
        run: uv run ruff format --check

      - name: Type check
        run: uv run mypy --strict src/

      - name: Test
        run: uv run pytest

      - name: Prune uv cache
        if: always()
        run: uv cache prune --ci
