name: Validate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  validate-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv (with cache)
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.16"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Create venv
        run: uv venv

      - name: Sync project (install deps)
        run: uv sync --locked --all-extras --dev

      - name: Lint
        run: uv run ruff check .

      - name: Check formatting
        run: uv run ruff format --check

      - name: Type check
        run: uv run mypy --strict src/

      - name: Test
        run: uv run pytest

      - name: Prune uv cache
        if: always()
        run: uv cache prune --ci
