name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: '3.x'
      - name: Install dependencies
        run: |
          task install
          task install-dev
      - name: Lint
        run: task lint
      - name: Check formatting
        run: task format -- --check
      - name: Type check
        run: task typecheck
      - name: Test
        run: task test
